# Develop
FROM arm64v8/node:14-buster

RUN git clone https://github.com/recipe4m/recipe4m-api.git -b develop app

WORKDIR /app

RUN yarn --network-timeout 600000

ENTRYPOINT git pull && yarn --network-timeout 600000 && yarn prisma:pull && yarn start:dev